# Generated by Django 5.1.1 on 2024-09-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='News title')),
                ('short_description', models.CharField(max_length=200, verbose_name='Short news description')),
                ('text', models.TextField(verbose_name='News text')),
                ('pub_date', models.DateTimeField(verbose_name='Date of publication')),
            ],
        ),
    ]
